In [14]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import IsolationForest
from numba import vectorize
import pandas as pd
import numpy as np

In [15]:
import warnings  
warnings.filterwarnings("ignore")

In [16]:
df = pd.read_csv('iforest_projetct.csv')
df

,Unnamed: 0,H,M,S,Nome,Maquina,IP,Anomalia,Fator_risco
0,0,16,29,4,theteacher@empresax.COM.BR,empresaxLAB02$,192.168.100.57,0,9.976591
1,1,14,12,4,pogó@empresax.COM.BR,empresaxLAB05$,192.168.100.66,0,0.135956
2,2,12,55,4,jinx@empresax.COM.BR,empresaxLAB03$,192.168.100.60,0,23.724740
3,3,18,22,4,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.100.55,0,7.539249
4,4,12,3,4,maryjane@empresax.COM.BR,empresaxLAB04$,192.168.100.58,0,24.796953
...,...,...,...,...,...,...,...,...,...
1097,1097,18,18,3,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.100.54,0,2.320827
1098,1098,19,4,3,theteacher@empresax.COM.BR,empresaxLAB02$,192.168.100.58,0,52.354812
1099,1099,13,53,3,dora@empresax.COM.BR,empresaxNOTE-LAB03$,192.168.100.60,0,28.734630
1100,1100,14,30,3,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.68,0,6.448798
1101,1101,18,27,3,maryjane@empresax.COM.BR,empresaxLAB04$,192.168.100.62,0,9.640242

In [17]:
df[df['Anomalia'] == 1]

,Unnamed: 0,H,M,S,Nome,Maquina,IP,Anomalia,Fator_risco
6,6,22,52,4,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,NaN
31,31,2,37,2,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,96.335442
42,42,13,23,5,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.68,1,20.298826
69,69,1,23,2,pogó@empresax.COM.BR,empresaxLAB05$,192.168.100.66,1,92.724826
87,87,19,43,4,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.68,1,59.538156
100,100,19,43,4,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.68,1,55.953780
107,107,11,50,5,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.109.52,1,6.866154
115,115,15,1,5,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.109.52,1,7.016449
123,123,20,12,3,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.68,1,50.440617
186,186,23,37,6,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,NaN
198,198,3,19,2,pogó@empresax.COM.BR,empresaxLAB05$,192.168.100.66,1,98.300823
211,211,22,7,2,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,NaN
216,216,22,56,2,jinx@empresax.COM.BR,empresaxLAB03$,192.168.100.60,1,NaN
217,217,23,3,2,theteacher@empresax.COM.BR,empresaxLAB02$,192.168.100.57,1,NaN
271,271,23,23,0,magaiver@empresax.COM.BR,empresaxWKS14A$,192.168.109.64,1,NaN
307,307,20,1,5,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.100.59,1,52.846978
308,308,20,25,5,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.68,1,55.103122
343,343,3,22,4,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,96.218766
347,347,13,5,5,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.109.52,1,37.113799
406,406,2,4,6,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,94.766686
422,422,3,52,6,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,90.615115
431,431,23,13,4,hanskelsen@empresax.COM.BR,empresaxWKS05$,192.168.100.59,1,NaN
452,452,17,23,5,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.71,1,5.842903
458,458,20,19,0,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.109.52,1,53.199452
459,459,23,11,4,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN
538,538,3,7,4,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,99.179180
540,540,23,11,4,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN
553,553,23,11,4,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN
559,559,22,36,2,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.100.56,1,NaN
565,565,23,14,2,hanskelsen@empresax.COM.BR,empresaxWKS05$,192.168.100.59,1,NaN
601,601,20,9,4,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.71,1,53.879109
611,611,2,22,2,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,93.386296
622,622,19,31,1,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.71,1,54.275049
627,627,4,7,6,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,99.345431
631,631,23,22,6,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,NaN
730,730,23,42,2,jinx@empresax.COM.BR,empresaxLAB03$,192.168.100.60,1,NaN
753,753,22,51,2,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN
785,785,22,51,2,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN
794,794,20,31,2,backwidow@empresax.COM.BR,empresaxWKSS06$,192.168.100.71,1,58.176640
911,911,1,19,4,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,92.897765
912,912,4,52,1,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,96.600972
957,957,5,49,3,mutley@empresax.COM.BR,HYPERV$,192.168.102.221,1,97.311891
962,962,22,7,2,hanskelsen@empresax.COM.BR,empresaxWKS05$,192.168.100.59,1,NaN
963,963,23,0,2,laracroft@empresax.COM.BR,empresaxWKS13A$,192.168.100.64,1,NaN
965,965,23,7,2,magaiver@empresax.COM.BR,empresaxWKS14A$,192.168.100.51,1,NaN
966,966,23,52,2,laracroft@empresax.COM.BR,empresaxWKS13A$,192.168.100.64,1,NaN
975,975,0,8,3,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.100.56,1,NaN
986,986,22,58,2,kael-el@empresax.COM.BR,empresaxWKSLEN02$,192.168.100.56,1,NaN
987,987,22,56,2,maryjane@empresax.COM.BR,empresaxLAB04$,192.168.100.58,1,NaN
990,990,22,51,2,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN
1062,1062,22,34,3,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN
1072,1072,22,34,3,hanskelsen@empresax.COM.BR,HYPERV$,192.168.100.64,1,NaN

In [5]:
df.drop(columns= ['Unnamed: 0'] , axis = 1, inplace = True)

In [6]:
df.dropna(inplace=True)

In [7]:
ordinalEncoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-99).fit(df[['Nome', 'Maquina','IP']])
df[['Nome', 'Maquina','IP']] = ordinalEncoder.transform(df[['Nome', 'Maquina','IP']])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1059 entries, 0 to 1101
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   H            1059 non-null   int64
 1   M            1059 non-null   int64
 2   S            1059 non-null   int64
 3   Nome         1059 non-null   float64
 4   Maquina      1059 non-null   float64
 5   IP           1059 non-null   float64
 6   Anomalia     1059 non-null   int64
 7   Fator_risco  1059 non-null   float64
dtypes: float64(4), int64(4)
memory usage: 74.5 KB

In [9]:
df[['Nome', 'Maquina','IP']] = df[['Nome', 'Maquina','IP']].astype(int)

In [10]:
df_apply = df.copy(deep = True)

In [11]:
df_apply

       H   M  S  Nome  Maquina  IP  Anomalia  Fator_risco
0     16  29  4    13        2   6         0     9.976591
1     14  12  4    11        5  15         0     0.135956
2     12  55  4     4        3   9         0    23.724740
3     18  22  4     5       13   4         0     7.539249
4     12   3  4     8        4   7         0    24.796953
...   ..  .. ..   ...      ...  ..       ...          ...
1097  18  18  3     5       13   3         0     2.320827
1098  19   4  3    13        2   7         0    52.354812
1099  13  53  3     2        6   9         0    28.734630
1100  14  30  3     0       14  17         0     6.448798
1101  18  27  3     8        4  11         0     9.640242

[1059 rows x 8 columns]

In [12]:
df[df['Anomalia'] == 1]

      H   M  S  Nome  Maquina  IP  Anomalia  Fator_risco
31    2  37  2    10        0  27         1    96.335442
42   13  23  5     0       14  17         1    20.298826
69    1  23  2    11        5  15         1    92.724826
87   19  43  4     0       14  17         1    59.538156
100  19  43  4     0       14  17         1    55.953780
107  11  50  5     5       13  28         1     6.866154
115  15   1  5     5       13  28         1     7.016449
123  20  12  3     0       14  17         1    50.440617
198   3  19  2    11        5  15         1    98.300823
307  20   1  5     5       13   8         1    52.846978
308  20  25  5     0       14  17         1    55.103122
343   3  22  4    10        0  27         1    96.218766
347  13   5  5     5       13  28         1    37.113799
406   2   4  6    10        0  27         1    94.766686
422   3  52  6    10        0  27         1    90.615115
452  17  23  5     0       14  20         1     5.842903
458  20  19  0     5       13  28         1    53.199452
538   3   7  4    10        0  27         1    99.179180
601  20   9  4     0       14  20         1    53.879109
611   2  22  2    10        0  27         1    93.386296
622  19  31  1     0       14  20         1    54.275049
627   4   7  6    10        0  27         1    99.345431
794  20  31  2     0       14  20         1    58.176640
911   1  19  4    10        0  27         1    92.897765
912   4  52  1    10        0  27         1    96.600972
957   5  49  3    10        0  27         1    97.311891

In [94]:
def categ(row):
    if row['Fator_risco']<=10:
        return 1
    elif row['Fator_risco']<=20:
        return 2
    elif row['Fator_risco']<=30:
        return 3
    elif row['Fator_risco']<=40:
        return 4
    elif row['Fator_risco']<=50:
        return 5
    elif row['Fator_risco']<=60:
        return 6
    elif row['Fator_risco']<=70:
        return 7
    elif row['Fator_risco']<=80:
        return 8
    elif row['Fator_risco']<=90:
        return 9
    else:
        return 10

In [95]:
df['Fator_risco'].values
#df['Fator_risco'] = categ(df.values)

array([ 9.97659072,  0.1359556 , 23.72473995, ..., 28.73463029,
        6.44879751,  9.64024201])

In [96]:
@vectorize(nopython=True, cache=True)
def categ1(i):
    
    if i<= 10.0:return 1
    elif i<=20.0:return 2
    elif i<=30.0:return 3
    elif i<=40.0:return 4
    elif i<=50.0:return 5
    elif i<=60.0:return 6
    elif i<=70.0:return 7
    elif i<=80.0:return 8
    elif i<=90.0:return 9
    else:return 10

RuntimeError: cannot cache function 'categ1': no locator available for file '/var/folders/sw/sh2714250jz1ndmsz1dv6xqc0000gn/T/ipykernel_76181/1213385674.py'

In [55]:
%%time
df['Fator_risco'] = categ1(df['Fator_risco'].values)

CPU times: total: 31.2 ms
Wall time: 28.6 ms

In [57]:
X = df.drop('Anomalia', axis = 1)

In [58]:
X

       H   M  S  Nome  Maquina  IP  Fator_risco
0     16  29  4    13        2   6            1
1     14  12  4    11        5  15            1
2     12  55  4     4        3   9            3
3     18  22  4     5       13   4            1
4     12   3  4     8        4   7            3
...   ..  .. ..   ...      ...  ..          ...
1097  18  18  3     5       13   3            1
1098  19   4  3    13        2   7            6
1099  13  53  3     2        6   9            3
1100  14  30  3     0       14  17            1
1101  18  27  3     8        4  11            1

[1059 rows x 7 columns]

In [67]:
%%time
iforest = IsolationForest(n_estimators=200, max_samples=0.1, contamination=0.05, max_features=1.0, bootstrap=False, n_jobs=-1, 
                            random_state=None, verbose=0, warm_start=False).fit(X)

CPU times: total: 688 ms
Wall time: 413 ms

In [68]:
results = iforest.predict(X)

In [69]:
results = np.where(results == 1, 0, 1)

In [70]:
from sklearn.metrics import classification_report
print(classification_report(results, df['Anomalia']))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1006
           1       0.58      0.28      0.38        53

    accuracy                           0.95      1059
   macro avg       0.77      0.64      0.68      1059
weighted avg       0.94      0.95      0.95      1059