In [137]:
import pandas as pd
import numpy as np
import bz2
import _pickle as cPickle
import pickle

In [138]:
def decompress_pickle(file):
    data = bz2.BZ2File(file, 'rb')
    data = cPickle.load(data)
    return data

In [139]:
def compressed_pickle(title, data):
    with bz2.BZ2File(title + '.pbz2', 'w') as f:
        cPickle.dump(data, f)
    return data

In [158]:
prepro_base = pd.read_csv('prepro.csv')

/Users/vtrferreira/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [159]:
prepro_base

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0,11.069319725036621,0.569882333278656,0.6066802144050598,5.752928256988525,0.07693725824356079,5.904725551605225,40.68379211425781,0.9953150153160095,2.952591896057129,0.8822433352470398,11.943900108337402
1,1,12.449566841125488,0.29539671540260315,0.14941424131393433,5.89582633972168,0.08110009878873825,40.939048767089844,14.018003463745117,0.9915151000022888,3.5888054370880127,0.7083103656768799,13.923818588256836
2,2,12.45242691040039,0.8361951112747192,0.25983360409736633,6.141569137573242,0.07715343683958054,6.395565509796143,84.78874206542969,0.9976242780685425,3.6642587184906006,0.7407566905021667,13.863845825195312
3,3,8.862597465515137,0.538851797580719,0.164982870221138,2.89052677154541,0.05743861198425293,9.873711585998535,32.35454177856445,0.9923511147499084,3.6049082279205322,0.663860023021698,13.257110595703125
4,4,7.630237579345703,0.6930071711540222,0.7078503370285034,5.951973915100098,0.05577762424945831,21.772865295410156,65.73421478271484,0.9971920847892761,2.9819180965423584,0.8334466814994812,11.757081031799316
...,...,...,...,...,...,...,...,...,...,...,...,...
78612,78612,13.59576,10.355242,10.515774,12.473773,8.726988,14.607945,13.790157,11.287994,12.372958,11.138267,13.806882
78613,78613,13.542729,10.858724,9.284594,11.985019,8.833064,14.047969,15.727456,11.290536,12.385107,11.133432,13.58938
78614,78614,13.332156,10.766385,10.932289,13.062647,8.404769,14.051758,14.2708,11.290758,12.361561,11.084942,13.715393
78615,78615,13.140611,10.313539,10.784853,11.937643,8.241388,14.939779,14.38471,11.289416,12.528764,10.995229,13.621824
78616,78616,13.249433,10.283236,10.553615,12.891185,8.652452,14.154155,15.119147,11.290883,12.46417,11.351265,13.775845

In [31]:
prepro_base.head(10)

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0,11.069319725036621,0.569882333278656,0.6066802144050598,5.752928256988525,0.07693725824356079,5.904725551605225,40.68379211425781,0.9953150153160095,2.952591896057129,0.8822433352470398,11.943900108337402
1,1,12.449566841125488,0.29539671540260315,0.14941424131393433,5.89582633972168,0.08110009878873825,40.939048767089844,14.018003463745117,0.9915151000022888,3.5888054370880127,0.7083103656768799,13.923818588256836
2,2,12.45242691040039,0.8361951112747192,0.25983360409736633,6.141569137573242,0.07715343683958054,6.395565509796143,84.78874206542969,0.9976242780685425,3.6642587184906006,0.7407566905021667,13.863845825195312
3,3,8.862597465515137,0.538851797580719,0.164982870221138,2.89052677154541,0.05743861198425293,9.873711585998535,32.35454177856445,0.9923511147499084,3.6049082279205322,0.663860023021698,13.257110595703125
4,4,7.630237579345703,0.6930071711540222,0.7078503370285034,5.951973915100098,0.05577762424945831,21.772865295410156,65.73421478271484,0.9971920847892761,2.9819180965423584,0.8334466814994812,11.757081031799316
5,5,10.258370399475098,0.45849111676216125,0.34168869256973267,1.9848941564559937,0.07795725017786026,33.15117645263672,15.664664268493652,0.9920913577079773,3.370849847793579,0.778762698173523,11.631134033203125
6,6,12.594608306884766,0.46156108379364014,0.32923412322998047,6.249478340148926,0.07064841687679291,27.884971618652344,16.345191955566406,0.991819441318512,3.4078941345214844,0.7988008856773376,13.440825462341309
7,7,8.700425148010254,0.3598610460758209,0.20739968121051788,2.689552068710327,0.07032489031553268,41.13349914550781,32.50288772583008,0.9916596412658691,3.55954909324646,0.8575019240379333,12.718114852905273
8,8,11.890785217285156,0.4248238801956177,0.10801820456981659,4.43077278137207,0.06991779059171677,41.38191604614258,78.07440948486328,0.9914290904998779,3.7102386951446533,0.9153856635093689,13.105633735656738
9,9,5.408064842224121,0.6140835881233215,0.7161311507225037,1.4386396408081055,0.05735750123858452,41.00164031982422,12.701509475708008,0.9985889792442322,2.88462495803833,1.0098797082901,9.801990509033203

In [32]:
prepro_base.tail(10)

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
78607,78607,13.608568,10.950244,9.05556,13.019227,8.740032,14.795982,15.643705,11.287065,12.599367,11.273326,13.907122
78608,78608,13.637921,10.943427,9.508077,12.830715,8.775278,12.996807,14.993319,11.289514,12.390679,10.982796,13.759063
78609,78609,13.196795,10.554955,10.832558,11.654039,8.688603,14.989108,14.55175,11.293449,12.358443,11.277627,13.578457
78610,78610,13.423058,10.925192,10.265537,12.803325,8.545899,14.724407,15.765618,11.293016,12.592106,11.366791,13.695754
78611,78611,13.732118,11.074729,8.997648,13.060686,8.789947,12.648816,15.714561,11.290837,12.548247,11.128544,13.931362
78612,78612,13.59576,10.355242,10.515774,12.473773,8.726988,14.607945,13.790157,11.287994,12.372958,11.138267,13.806882
78613,78613,13.542729,10.858724,9.284594,11.985019,8.833064,14.047969,15.727456,11.290536,12.385107,11.133432,13.58938
78614,78614,13.332156,10.766385,10.932289,13.062647,8.404769,14.051758,14.2708,11.290758,12.361561,11.084942,13.715393
78615,78615,13.140611,10.313539,10.784853,11.937643,8.241388,14.939779,14.38471,11.289416,12.528764,10.995229,13.621824
78616,78616,13.249433,10.283236,10.553615,12.891185,8.652452,14.154155,15.119147,11.290883,12.46417,11.351265,13.775845

In [33]:
prepro_base.describe()

         Unnamed: 0
count  78617.000000
mean   39308.000000
std    22694.917394
min        0.000000
25%    19654.000000
50%    39308.000000
75%    58962.000000
max    78616.000000

In [88]:
prepro_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78617 entries, 0 to 78616
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            78617 non-null  Int64
 1   fixed acidity         78617 non-null  object
 2   volatile acidity      78617 non-null  object
 3   citric acid           78617 non-null  object
 4   residual sugar        78617 non-null  object
 5   chlorides             78617 non-null  object
 6   free sulfur dioxide   78617 non-null  object
 7   total sulfur dioxide  78617 non-null  object
 8   density               78617 non-null  object
 9   pH                    78617 non-null  object
 10  sulphates             78617 non-null  object
 11  alcohol               78617 non-null  object
dtypes: Int64(1), object(11)
memory usage: 7.3+ MB

In [35]:
a = lambda x: str(x).split(',')
prepro_base['fixed acidity'].apply(a)

0        [11.069319725036621]
1        [12.449566841125488]
2         [12.45242691040039]
3         [8.862597465515137]
4         [7.630237579345703]
                 ...
78612     [13.59576012879686]
78613     [13.54272906113354]
78614    [13.332155953743444]
78615    [13.140610506908066]
78616    [13.249432900946054]
Name: fixed acidity, Length: 78617, dtype: object

In [103]:
prepro_base.loc[prepro_base.chlorides.astype(str).str.contains('12345')]

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
11156,11156,5.900754928588867,0.843481719493866,0.23768126964569092,4.698594093322754,0.069540,5.4443745613098145,87.92860412597656,0.9978138208389282,3.520089864730835,0.930891215801239,11.222047805786133
13140,13140,11.555749893188477,0.37988659739494324,0,5.792325019836426,0.061235,40.99189758300781,42.09935760498047,0.9912205338478088,3.6896886825561523,0.700757622718811,13.841097831726074
39108,39108,6.437241077423096,0.8434985280036926,0.6823192238807678,0,0.053521,7.9557881355285645,84.21836853027344,0.9979856610298157,3.047530174255371,1.0609444379806519,10.39236068725586
42146,42146,12.132011413574219,0.44694387912750244,0.21204398572444916,3.5252909660339355,0.081235,6.8645548820495605,28.05706787109375,0.9944933652877808,2.923105001449585,0.7438489198684692,12.733614921569824
45428,45428,9.455260276794434,0.5032037496566772,0.19936181604862213,3.0794713497161865,0.061235,35.08810043334961,55.30431365966797,0.993789792060852,3.204608678817749,0.7532647848129272,10.467718124389648

In [77]:
prepro_base = prepro_base.replace(np.nan, 0)

In [89]:
prepro_base = prepro_base.convert_dtypes()

In [92]:
prepro_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78617 entries, 0 to 78616
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            78617 non-null  Int64
 1   fixed acidity         78617 non-null  object
 2   volatile acidity      78617 non-null  object
 3   citric acid           78617 non-null  object
 4   residual sugar        78617 non-null  object
 5   chlorides             78617 non-null  object
 6   free sulfur dioxide   78617 non-null  object
 7   total sulfur dioxide  78617 non-null  object
 8   density               78617 non-null  object
 9   pH                    78617 non-null  object
 10  sulphates             78617 non-null  object
 11  alcohol               78617 non-null  object
dtypes: Int64(1), object(11)
memory usage: 7.3+ MB

In [146]:
prepro_base['chlorides'] = prepro_base['chlorides'].str.strip('[]').astype(float)

In [147]:
prepro_base[prepro_base['chlorides'] == '[3897]']

Empty DataFrame
Columns: [Unnamed: 0, fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol]
Index: []

In [188]:
prepro_base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78617 entries, 0 to 78616
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            78617 non-null  float64
 1   fixed acidity         78590 non-null  float64
 2   volatile acidity      78599 non-null  float64
 3   citric acid           78583 non-null  float64
 4   residual sugar        78590 non-null  float64
 5   chlorides             78595 non-null  float64
 6   free sulfur dioxide   78601 non-null  float64
 7   total sulfur dioxide  78593 non-null  float64
 8   density               78592 non-null  float64
 9   pH                    78600 non-null  float64
 10  sulphates             78588 non-null  float64
 11  alcohol               78587 non-null  float64
dtypes: float64(12)
memory usage: 7.2 MB

In [186]:
for i in prepro_base.columns:
    prepro_base[i] = prepro_base[i].apply(lambda x: str(x).replace('[','').replace(']',''))
    prepro_base[i] = prepro_base[i].astype(float)

In [189]:
prepro_base

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.0,11.069320,0.569882,0.606680,5.752928,0.076937,5.904726,40.683792,0.995315,2.952592,0.882243,11.943900
1,1.0,12.449567,0.295397,0.149414,5.895826,0.081100,40.939049,14.018003,0.991515,3.588805,0.708310,13.923819
2,2.0,12.452427,0.836195,0.259834,6.141569,0.077153,6.395566,84.788742,0.997624,3.664259,0.740757,13.863846
3,3.0,8.862597,0.538852,0.164983,2.890527,0.057439,9.873712,32.354542,0.992351,3.604908,0.663860,13.257111
4,4.0,7.630238,0.693007,0.707850,5.951974,0.055778,21.772865,65.734215,0.997192,2.981918,0.833447,11.757081
...,...,...,...,...,...,...,...,...,...,...,...,...
78612,78612.0,13.595760,10.355242,10.515774,12.473773,8.726988,14.607945,13.790157,11.287994,12.372958,11.138267,13.806882
78613,78613.0,13.542729,10.858724,9.284594,11.985019,8.833064,14.047969,15.727456,11.290536,12.385107,11.133432,13.589380
78614,78614.0,13.332156,10.766385,10.932289,13.062647,8.404769,14.051758,14.270800,11.290758,12.361561,11.084942,13.715393
78615,78615.0,13.140611,10.313539,10.784853,11.937643,8.241388,14.939779,14.384710,11.289416,12.528764,10.995229,13.621824
78616,78616.0,13.249433,10.283236,10.553615,12.891185,8.652452,14.154155,15.119147,11.290883,12.464170,11.351265,13.775845